### ISSUE TITLE
Add Rasto Bencel to "Our Team" section

### ISSUE THREAD

**Issue by Horkyze** [MWGA/mwga#5]

**Comment by xhesek** [comment]
Everything OK.

**Comment by MisoHampel** [comment]
Mistake in Rastislav name

**Comment by MisoHampel** [comment]
Issue fixed.
Merged to master.

**Comment by Horkyze** [comment]
Toto bola pekna ukazka hotfixu, commit priamo do mastra 🔨 
https://github.com/MWGA/www/commit/8642ceaa92d082409524bdc22e0c8db12c44f6d9
Mali by sme sa potom dohodnut, ci taketo veci mozeme robit

**Comment by MisoHampel** [comment]
Jop. Ospravedlnujem sa za to ... chyba mi tam hlaska ci to naozaj chcem mergnut do mastra :) Priamo by sa to nemalo robit!
