### ISSUE TITLE
Sniffing WiFi traffic

### ISSUE THREAD

**Issue by Horkyze** [MWGA/mwga#51]
Zapnuty monitor mode:

`airmon-ng wlan0 up` -> monitor mode enabled at `mon0`
Nastavim channel `iwconfig wlx004f81048a95 freq 2.472G` -> moja wifi doma (13. kanal)

Vo wiresharku vidim len beacon frames, ziadne data, ak ked spustim youtube video na telefone (ktory je pripojeny na tej wifine).

Kde je chyba?

**Comment by proocho** [comment]
dáta sú zakryptované
dá sa to odkryptovať: https://wiki.wireshark.org/HowToDecrypt802.11

**Comment by Horkyze** [comment]
ale ja to nechcem dekryptovat, nech ich len ukaze, ak ked su zasifrovane..

**Comment by proocho** [comment]
Some common mistakes are:

   *  Not capturing all 4 EAPOL frames. To do this, you need to capture frames when the client first associates to the WLAN
   *  Not enabling the WLAN decryption option in Wireshark
   *  Toggling the decryption option on to off then back on again.
